"""
Django settings for VolvoSkin project.

Generated by 'django-admin startproject' using Django 1.11.14.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kpdmh4&7$6=wdc##&e4xfzwf@lt7%!@q%2(s6c^b0%#n8$2wx('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'oauth2_provider',
    'rest_framework',

    'storages',

    "commons.user_auth",
    "commons.position",

    "cv360.mobile.account",
    "cv360.mobile.opty",
    "fcm"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VolvoSkin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VolvoSkin.wsgi.application'
SERVER_PROTOCOLS = "http://"


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myvolvodb',
        'USER': 'newuser',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CLIENT_ID = '11z6OvuOkV8Y6xCQjcQINvYMqFDx2I71rAkHeNsq'
CLIENT_SECRET = 'VDl4sDGtzhe9gJ0EBZcp7Fhh5lMgz8IGKPkg8eFgON27woxgcbeDoTEOQMxiEtBBAn0C8zAAe4YFpYX9zBapaWN5QjDRKlXxm0uKVIJzAbkw4hsI3qbHGaUwskdxybrT'

OAUTH2_PROVIDER = {
    ## Oauth Token expiry time configuration
    'ACCESS_TOKEN_EXPIRE_SECONDS': 600000
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

# AWS HEADER
AWS_HEADERS = {
# see http://developer.yahoo.com/performance/rules.html#expires
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'Cache-Control': 'max-age=94608000',
}

# AWS S3 Buckets Details
AWS_STORAGE_BUCKET_NAME = 'audetemidev'
AWS_ACCESS_KEY_ID = 'AKIAILXKHBQJLB22VRUQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_DEFAULT_ACL = "public-read"

STATICFILES_LOCATION = 'static'
STATIC_ROOT = "/var/www/Web/static/"

MEDIAFILES_LOCATION = 'media'
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
DEFAULT_FILE_STORAGE = 'volvo_skin.custom_storages.MediaStorage'
# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'



ACCOUNT_LOGFILE_NAME = "/tmp/log/volvo_skin/accounts_errors.log"
OPTY_LOGFILE_NAME = "/tmp/log/volvo_skin/opty_errors.log"
USER_LOGFILE_NAME = "/tmp/log/volvo_skin/user_errors.log"
POSITION_LOGFILE_NAME = "/tmp/log/volvo_skin/position_errors.log"
LOGFILE_SIZE = 5 * 1024 * 1024
LOGFILE_COUNT = 5

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s ' + ' [%(name)s.%(funcName)s:%(lineno)d] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'development_log': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/tmp/log/skin_errors.log',
            'formatter': 'simple'
        },
        'account_log': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': LOGFILE_SIZE,
            'backupCount': LOGFILE_COUNT,
            'filename': ACCOUNT_LOGFILE_NAME,
            'formatter': 'simple'
        },
        'opty_log': {
                'level': 'DEBUG',
                'class': 'logging.handlers.RotatingFileHandler',
                'maxBytes': LOGFILE_SIZE,
                'backupCount': LOGFILE_COUNT,
                'filename': OPTY_LOGFILE_NAME,
                'formatter': 'simple'
        },
        'user_log': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': LOGFILE_SIZE,
            'backupCount': LOGFILE_COUNT,
            'filename': USER_LOGFILE_NAME,
            'formatter': 'simple'
        },
        'position_log': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': LOGFILE_SIZE,
            'backupCount': LOGFILE_COUNT,
            'filename': POSITION_LOGFILE_NAME,
            'formatter': 'simple'
        },

    },
    'loggers': {
        'entity': {
            'handlers': ['development_log'],
            'level': 'ERROR'
        },
        'django.request': {
            'handlers': ['development_log'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['development_log'],
            'propagate': False,
            'level': 'ERROR',
        },
        'account': {
            'handlers': ['account_log'],
            'level': 'DEBUG'
        },
        'opty': {
            'handlers': ['opty_log'],
            'level': 'DEBUG'
        },
        'user_auth': {
            'handlers': ['user_log'],
            'level': 'DEBUG'
        },
        'position': {
            'handlers': ['position_log'],
            'level': 'DEBUG'
        },


    }
}

FCM_APIKEY = "AAAAJqZSOX4:APA91bFJY84HFb96VGAVLPyVuy2xVijL1YVjLEh5Zw3Cm59sh4b0bMRktE8dUDOVRO0i0gN30Zy6RNjF-1Nfesfr5I2rwfiTbcm6We3KjCfFnYKEOeXJ4-zfkYjoGv7YGNISbfXyN9uD"

FCM_MAX_RECIPIENTS = "500000"

EMAIL_USE_TLS = True

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_HOST_USER = 'audetemidemo@gmail.com'

EMAIL_HOST_PASSWORD = 'audetemi@demo'

EMAIL_PORT = 587

VOLVO_CLIENT_ID = "ScoutMobileQA"

VOLVO_CLIENT_SECRET = "7SeNvma8jINqaA39wVuTl7b6841hVA7vfuRcFmq4rgd1txvuzLIGhU5M3GL4BLss"
