# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_userprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
