# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emp_desig',
            field=models.CharField(default='developer', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emp_id',
            field=models.IntegerField(default=0),
        ),
    ]
