# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('upto_date', models.DateField()),
                ('calculated_leaves', models.IntegerField()),
                ('reason', models.CharField(max_length=2000)),
            ],
        ),
    ]
